name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag email-groups
      - name: Run the Docker image
        run: docker run email-groups
      - name: Creating .tar of docker image
        run: docker save email-groups > email-groups.tar
      - name: Download .tar of docker image
        uses: actions/upload-artifact@v1
        with:
          name: Image
          path: email-groups.tar
